[project]
name = "dev-shell"
version = "0.1.0"
description = "A custom developer shell for file, system, and server operations"
readme = "README.md"
requires-python = ">=3.10"

# license = "MIT"

authors = [{ name = "sachinggsingh" }]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  # "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

keywords = [
  "cli",
  "developer-tools",
  "file-manager",
  "monitoring-tool",
  "server-operations",
  "shell",
]

dependencies = [
  "psutil",
  "requests",
]

[project.urls]
"Bug Tracker" = "https://github.com/sachinggsingh/Dev_Shell/issues"
Homepage = "https://github.com/sachinggsingh/Dev_Shell"

[project.scripts]
dev-shell = "dev_shell.cli:main"

[project.optional-dependencies]
dev = [
  "ruff",
  "pylint",
  "pytest",
  "build",
  "twine",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dev_shell = [
  "config/*.json",
]


# ============================================================================
# Ruff
# ============================================================================

[tool.ruff]
line-length = 88
target-version = "py310"

exclude = [
  ".git",
  ".venv",
  "venv",
  "build",
  "dist",
  "__pycache__",
]

[tool.ruff.lint]
select = [
  "E",      # pycodestyle
  "F",      # Pyflakes
  "I",      # isort
  "B",      # flake8-bugbear
  "UP",     # pyupgrade
  "BLE",    # blind-except
  "DTZ",    # datetime timezone
  "PLW",    # Pylint warnings
  "RUF",    # Ruff-specific rules
  "TRY",    # tryceratops
  "S",      # flake8-bandit
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"